Development export
ALLHUBS-Jan-2024-Liftoff/max-group-CJSY pull request #36
Opened 2024-07-21 19:03 UTC by UGcode101

2024-07-21 19:34 UTC, JenniferNedland requested changes
Yay thanks for doing all this

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/ThreemixApplication.java
> +	/*
Remove commented out code

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/PlaylistExportController.java
> +    private final RestTemplate restTemplate;
You can use @Autowired instead of initializing through the constructor

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/PlaylistExportController.java
> +    @CrossOrigin(origins = "*")
Use actual front-end URL rather than *

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/PlaylistExportController.java
> +    @GetMapping(value = "/getPlaylistDetails", produces = "application/json")
We are not fetching playlists from spotify, we will use recommendations to generate lists of tracks. change endpoint to /generateTrackList 
Front-end will call back end with three chosenGenres and backend will use spotify API to create playlist taking user's blocked artists and songs into account.

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/StateController.java
> +    @GetMapping(value = "/generateState")
This should not be an endpoint. Remove annotations. They are helper functions.

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/StateController.java
> +@RestController
This should not be an endpoint. Remove annotations. They are helper functions.

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/StateController.java
> +    @GetMapping(value = "/validateState")
This should not be an endpoint. Remove annotations. They are helper functions.

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/ThreemixController.java
> +    private static final String SCOPE = "user-read-private user-read-email playlist-modify-private playlist-modify-public";
Private final variables should be camelCase

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/ThreemixController.java
> +                        accessTokenCookie.setHttpOnly(true);
Remove httpOnly setting so it can be used by javascript

2024-07-21 19:34 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/ThreemixController.java
> +    private StateController stateController;
You can use the StateService directly, since the state controller don't add value. Remove StateController and add Autowired StateService

2024-07-22 01:56 UTC, UGcode101 commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/PlaylistExportController.java
> +    @GetMapping(value = "/getPlaylistDetails", produces = "application/json")
That means in the export controller Ill need a Blocked list Service and a Spotify Recommendation Service, and that would require a class for each respectively. And I believe Ill need a repository for the block list

2024-07-22 12:32 UTC, JenniferNedland reviewed
Great progress!

2024-07-22 12:32 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/PlaylistExportController.java
> +            url.append("&seed_artists=").append(String.join(",", blockedList.get("artists")));
This would give us tracks from the blocked artists or from similar artists, which is the opposite of what we want.
We need to first get the recommendations from Spotify, and then filter them on our end.

2024-07-22 12:32 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/ThreemixController.java
> +        String state = stateService.generateState(String.valueOf(session));
Use `session.getId()`

2024-07-22 12:32 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/ThreemixController.java
> +        if (!stateService.validateState(state, String.valueOf(session))) {
Also use `session.getId()`

2024-07-23 19:37 UTC, JenniferNedland reviewed
This looks good! 

I made one suggestion for a shorter solution and tried to clarify my session id comment.

2024-07-23 19:37 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/PlaylistExportController.java
> +                .collect(Collectors.toList());
FYI: You can use `.toList()` instead of `.collect(Collectors.toList())`.

2024-07-23 19:37 UTC, JenniferNedland commented on threemix-backend/src/main/java/org/launchcode/threemix/controller/ThreemixController.java
> +        String state = stateService.generateState(String.valueOf(session));
`String.valueOf(session)` will give you a string representation of the entire session object, instead of just the id that we are interested in.

I did a quick test using `System.out.println`, and `String.valueOf(session)` prints `org.apache.catalina.session.StandardSessionFacade@64a280ad`
while `session.getId()` prints `64975C6EE45CBCA65A9190146FD2E78C`

2024-07-23 20:04 UTC, JenniferNedland approved these changes
I was using this code and fixed the remaining issues to get it working.

2024-07-23 20:07 UTC, JenniferNedland approved these changes

2024-07-23 22:34 UTC, merged